require('dotenv').config();
const express = require('express'), cors = require('cors');
const connectDB = require('./config/database');
const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ limit: '10mb', extended: true }));
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/complaints', require('./routes/complaintRoutes'));
app.use('/api/ai', require('./routes/aiRoutes'));
app.use('/api/admin', require('./routes/adminRoutes'));
connectDB().then(() => app.listen(process.env.PORT || 5000, () => console.log('API running')));
